# Site settings
title: Skorpion Software Blog
email: bob@skorpionsoftware.com
description: > # this means to ignore newlines until "baseurl:"
  We love learning new things and we love teaching others new things.  Here is where we will share our experiences in the hope that they will help others :)
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://skorpionsoftware.com" # the base hostname & protocol for your site
twitter_username: skorpiontweets
# facebook_username:  jekyll

# Build settings
markdown: kramdown
